# Generated by Django 5.1 on 2024-09-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='leads',
        ),
        migrations.AddField(
            model_name='product',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_leads', to='product.leads'),
        ),
    ]
