# Generated by Django 5.1 on 2024-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_leads_product_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='leads',
        ),
        migrations.AddField(
            model_name='product',
            name='leads',
            field=models.ManyToManyField(related_name='product_leads', to='product.leads'),
        ),
    ]
